#server:
#  port: 10030
#spring:
#  application:
#    name: aikuiba-fccar-service-uaa
#  cloud:
#    nacos:
#      discovery:
#        namespace: fccar-dev
#        server-addr: 47.109.72.16:8848
#  datasource:
#    username: root
#    password: blt2021!@
#    url: jdbc:mysql://47.109.72.16:3306/aikuiba-fccar-uaa?serverTimezone=Asia/Shanghai&characterEncoding=utf8
#    driver-class-name: com.mysql.jdbc.Login
#    type: com.alibaba.druid.pool.DruidDataSource # 配置阿里的连接池
#    druid: # Druid 【监控】相关的全局配置
#      # 配置初始化大小、最小、最大
#      initial-size: 5
#      minIdle: 10
#      max-active: 20
#      # 配置获取连接等待超时的时间(单位：毫秒)
#      max-wait: 60000
#      ########### 启用内置过滤器（第一个 stat必须，否则监控不到SQL）##########
#      filters: stat,wall,log4j2
#      web-stat-filter:
#        enabled: true
#      stat-view-servlet:
#        enabled: true
#        allow: # 设置白名单，不填则允许所有访问
#        url-pattern: /druid/*
#        login-username: fccar # 控制台管理用户名和密码
#        login-password: fccar
#      filter:
#        stat:
#          enabled: true
#          log-slow-sql: true # 慢 SQL 记录
#          slow-sql-millis: 2000
#          merge-sql: true
#        wall:
#          config:
#            multi-statement-allow: true
## mybatis-plus配置
#mybatis-plus:
#  type-aliases-package: cn.aikuiba.domain,cn.aikuiba.query #别名包扫描
#  mapper-locations: classpath:cn/aikuiba/mapper/*Mapper.xml #SQL映射文件扫描
#  global-config:
#    db-config: #设置逻辑删除,通过把delete字段改成0而不是直接删除数据
#      logic-not-delete-value: 0
#      logic-delete-value: 1
#  configuration:
#    map-underscore-to-camel-case: true # 开启驼峰命名转换法
#    cache-enabled: false #禁用缓存
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 配置日志，在控制台输出SQL
## springdoc-openapi项目配置
#springdoc:
#  swagger-ui:
#    path: /doc.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#  api-docs:
#    path: /v3/api-docs/default
#
## knife4j的增强配置，不需要增强可以不配
#knife4j:
#  enable: true
#  setting:
#    language: zh_cn
#    swagger-model-name: 飞驰专车
#  basic:
#    enable: true
#    username: fccar
#    password: fccar
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # jwt秘钥，密钥任意配置
  jwt-secret-key: aikuiba
